# Primary inventory - AWS EC2 dynamic
# Requires: ansible-galaxy collection install amazon.aws
#           AWS credentials configured
plugin: amazon.aws.aws_ec2
regions:
  - eu-north-1
filters:
  tag:Project: afrimart
  instance-state-name: running
keyed_groups:
  - key: tags.Name
    prefix: name
hostnames:
  - public_ip_address
