apiVersion: v2
name: afrimart
description: AfriMart e-commerce platform Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - afrimart
  - ecommerce
maintainers:
  - name: AfriMart
    email: dev@afrimart.com
