---
- name: Install Nginx via amazon-linux-extras (AL2)
  ansible.builtin.command: amazon-linux-extras install nginx1 -y
  args:
    creates: /usr/sbin/nginx
  when: ansible_os_family == "RedHat"

- name: Create Nginx config for AfriMart
  ansible.builtin.template:
    src: afrimart.conf.j2
    dest: /etc/nginx/conf.d/afrimart.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart Nginx

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  ignore_errors: yes
  notify: Restart Nginx

- name: Enable and start Nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
